name: wallpaperflutter
description: A wallpaper app in flutter by Aakash.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  cached_network_image: ^2.2.0+1
  image_gallery_saver: ^1.5.0
  permission_handler: ^5.0.1+1
  random_string: ^2.0.1
  dio: ^3.0.9
  url_launcher: ^5.5.0
  flutter_staggered_grid_view: ^0.3.0
  settings_ui: ^0.3.0
  getwidget: ^1.1.0
  fluttertoast: ^6.0.0
  firebase_admob: ^0.9.3+2
  flutter_html: ^1.0.0
  about: ^1.1.2
  package_info: ^0.4.1
  flutter_native_splash: ^0.1.9




  cupertino_icons: ^0.1.3

flutter_native_splash:
  image: assets/images/splash.png
  color: "#F3E5F5"
  android_disable_fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google_fonts/


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/google_fonts/Raleway-Regular.ttf
        - asset: assets/google_fonts/Raleway-Italic.ttf
        - asset: assets/google_fonts/Raleway-Bold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
